import React from 'react';

export default function StarterCredit() {
    return (
        <aside className="starter-credit" aria-label="Starter kit credit">
            This site was generated by the{' '}
            <a href="https://github.com/flippydisk/nextjs-contentful-starter-kit" rel="noreferrer" target="_blank">
                Flippydisk NextJS + Contentful starter kit
            </a>
        </aside>
    );
}
